Update __init__.py
TO correct the error 
File "C:\Users\Deepak\Documents\GitHub\python-google-places\googleplaces\__init__.py", line 333, in radar_search
    self._request_params['location'] = lat_lng_str
TypeError: 'NoneType' object does not support item assignment